### ISSUE TITLE
Do not limit the target event

### ISSUE THREAD

**Issue by D4nte** [technote-space/package-version-check-action#168]
This action limits the user to specific target events.

If all the information needed to upgrade the version is passed to the action then it should not limit to a target event.

In my case, I just want an action to automate the update of the version in package.json.

I handle checkout, version selection and commit myself. However, I get a `> This is not target event.` event when [trying to use this action](https://github.com/comit-network/comit-js-sdk/runs/613821265?check_suite_focus=true).

My event is:
```
on:
  issues:
    types: [opened, reopened]
```

Could you review and consider not limiting the use of this action to specific event but instead check whether you have all the information necessary to proceed with the action?

Thanks.

**Comment by technote-space** [comment]
Not everyone can handle events, so I think this check is necessary.
You can use this action without checking like this:
```
      - name: Bump version in package.json
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1
          NEXT_VERSION: ${{ env.RELEASE_VERSION }}
          IGNORE_CONTEXT_CHECK: 1
```
