### ISSUE TITLE
Package Version Check Not Working?

### ISSUE THREAD

**Issue by samdevaprasadvarde** [technote-space/package-version-check-action#238]
I created a `.github/workflow/check_version.yml` file with content of this as shown in the README:

```
on: push
name: Check package version
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          BRANCH_PREFIX: release/
```

I see that it runs on my repo when I create a PR, but it shows as passing even though I didn't update the version in the package.json file.  How does this github action work and am I using it wrong?  Tried a few different variations with the "with:", but all in vain.
